export const formConfig = [
  {
    id: "firstname",
    label: "First Name",
    stageId: "basicDetails",
    componentType: "input",
    inputType: "text",
    required: true,
    minLength: 2,
    maxLength: 30,
    validation: { pattern: "^[A-Za-z]+$", message: "Only alphabets allowed" },
  },
  {
    id: "lastname",
    label: "Last Name",
    stageId: "basicDetails",
    componentType: "input",
    inputType: "text",
    required: true,
    minLength: 2,
    maxLength: 30,
    validation: { pattern: "^[A-Za-z]+$", message: "Only alphabets allowed" },
  },
  {
    id: "email",
    label: "Email",
    stageId: "basicDetails",
    componentType: "input",
    inputType: "email",
    required: true,
    validation: {
      pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$",
      message: "Enter a valid email address",
    },
  },
  {
    id: "dob",
    label: "Date of Birth",
    stageId: "basicDetails",
    componentType: "input",
    inputType: "date",
    required: true,
  },
  {
    id: "phoneCountry",
    label: "Country Code",
    stageId: "basicDetails",
    componentType: "select",
    inputType: "select",
    required: true,
    options: ["+64", "+960", "+950", "+67"],
  },
  {
    id: "number",
    label: "Phone Number",
    stageId: "basicDetails",
    componentType: "input",
    inputType: "tel",
    required: true,
    minLength: 10,
    maxLength: 10,
    validation: {
      pattern: "^[0-9]{10}$",
      message: "Enter a valid 10-digit number",
    },
  },
  {
    id: "gender",
    label: "Gender",
    stageId: "basicDetails",
    componentType: "select",
    inputType: "select",
    required: true,
    options: ["Male", "Female", "Other"],
  },
  {
    id: "address",
    label: "Address",
    stageId: "personalDetails",
    componentType: "textarea",
    inputType: "text",
    required: true,
    minLength: 10,
    maxLength: 100,
  },
  {
    id: "postalCode",
    label: "Postal Code",
    stageId: "personalDetails",
    componentType: "input",
    inputType: "text",
    required: true,
    validation: {
      pattern: "^[0-9]{6}$",
      message: "Enter a valid 6-digit postal code",
    },
  },
  {
    id: "poBox",
    label: "P.O. Box",
    stageId: "personalDetails",
    componentType: "input",
    inputType: "text",
    required: false,
  },
  {
    id: "city",
    label: "City",
    stageId: "personalDetails",
    componentType: "input",
    inputType: "text",
    required: true,
    validation: { pattern: "^[A-Za-z]+$", message: "Only alphabets allowed" },
  },
  {
    id: "mailingCity",
    label: "Mailing City",
    stageId: "personalDetails",
    componentType: "input",
    inputType: "text",
    required: false,
  },
  {
    id: "country",
    label: "Country",
    stageId: "personalDetails",
    componentType: "select",
    inputType: "text",
    required: true,
    options: ["India", "USA", "Canada", "China", "Russia"],
  },
  {
    id: "selfieUpload",
    label: "Upload a Selfie",
    stageId: "selfieStage",
    componentType: "selfie",
    required: true,
  },
  {
    id: "multipleNationalities",
    label: "Do you have multiple nationalities?",
    stageId: "taxInformation",
    componentType: "radio",
    inputType: "radio",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    id: "taxResidentOtherCountry",
    label: "Are you a tax resident of any other countries/ jurisdiction?",
    stageId: "taxInformation",
    componentType: "radio",
    inputType: "radio",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    id: "usPerson",
    label:
      "Are you a US Person(US Resident, US Citizen or US Green Card Holder)?",
    stageId: "taxInformation",
    componentType: "radio",
    inputType: "radio",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    id: "expectedDepositsCount",
    label: "Expected Total number of Deposits(per Month)",
    stageId: "employementInformation",
    componentType: "select",
    inputType: "select",
    required: true,
    options: ["1 to 10", "11 to 25", "26 to 50", "Above 50"],
    helpText: "Number of Deposits you expect monthly",
  },
  {
    id: "expectedDepositAmount",
    label: "Total Monthly Deposit Amount/ Value",
    stageId: "employementInformation",
    componentType: "input",
    inputType: "number",
    required: true,
    validation: { pattern: "^[0-9]+$", message: "Enter a valid number" },
    helpText: "Enter the total deposit amount per month",
  },
  {
    id: "expectedWithdrawalsCount",
    label: "Expected Total number of Withdrawals(per Month)",
    stageId: "employementInformation",
    componentType: "select",
    inputType: "select",
    required: true,
    options: ["1 to 10", "11 to 25", "26 to 50", "Above 50"],
    helpText: "Number of Withdrawals you expect monthly",
  },
  {
    id: "expectedWithdrawalAmount",
    label: "Total Monthly Withdrawal Amount/ Value",
    stageId: "employementInformation",
    componentType: "input",
    inputType: "number",
    required: true,
    validation: { pattern: "^[0-9]+$", message: "Enter a valid number" },
    helpText: "Enter the total withdrawal amount per month",
  },
];
